# EG10-18 Twinkle Twinkle
import time
import snaps

snaps.play_note(0)
time.sleep(0.4)
snaps.play_note(0)
time.sleep(0.4)
snaps.play_note(7)
time.sleep(0.4)
snaps.play_note(7)
time.sleep(0.4)
snaps.play_note(9)
time.sleep(0.4)
snaps.play_note(9)
time.sleep(0.4)
snaps.play_note(7)
time.sleep(0.8)
snaps.play_note(5)
time.sleep(0.4)
snaps.play_note(5)
time.sleep(0.4)
snaps.play_note(4)
time.sleep(0.4)
snaps.play_note(4)
time.sleep(0.4)
snaps.play_note(2)
time.sleep(0.4)
snaps.play_note(2)
time.sleep(0.4)
snaps.play_note(0)
time.sleep(0.8)
